# Generated by Django 3.2.7 on 2021-10-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0002_rename_userpreferences_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.CharField(blank=True, default='BMD - Bermudan Dollar', max_length=255, null=True),
        ),
    ]
